name: firebase_analytics_example
description: Demonstrates how to use the firebase_analytics plugin.

environment:
  sdk: ">=2.12.0-0 <3.0.0"
  flutter: ">=1.12.13+hotfix.5"

dependencies:
  e2e: ^0.6.1
  firebase_analytics:
    path: ../
  firebase_core:
    path: ../../../firebase_core/firebase_core
  flutter:
    sdk: flutter

# dependency_overrides:
#   firebase_core:
#     path: ../../../firebase_core/firebase_core
#   firebase_core_platform_interface:
#     path: ../../../firebase_core/firebase_core_platform_interface
#   firebase_core_web:
#     path: ../../../firebase_core/firebase_core_web

dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  pedantic: ^1.8.0
  test: any

flutter:
  uses-material-design: true
