name: firebase_analytics
description:
  Flutter plugin for Google Analytics for Firebase, an app measurement
  solution that provides insight on app usage and user engagement on Android and iOS.
homepage: https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_analytics/firebase_analytics
version: 7.1.1
publish_to: 'none'

environment:
  sdk: ">=2.12.0-0 <3.0.0"
  flutter: ">=1.12.13+hotfix.5"

dependencies:
  firebase_analytics_platform_interface: ^1.1.0
    # path: ../firebase_analytics_platform_interface/ 
  firebase_analytics_web: #^0.2.0+1
    git:
      url: https://github.com/wiseminds/flutterfire.git
      path: packages/firebase_analytics/firebase_analytics_web 
      ref: b2b39fc98fdf3ad2604d04aaf92bc06724cb6562   
    path: ../firebase_analytics_web/ 
  firebase_core: ^1.0.1
    # path: ../../firebase_core/firebase_core/
  flutter:
    sdk: flutter
  meta: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.0
  pedantic: ^1.8.0

flutter:
  plugin:
    platforms:
      android:
        package: io.flutter.plugins.firebaseanalytics
        pluginClass: FirebaseAnalyticsPlugin
      ios:
        pluginClass: FLTFirebaseAnalyticsPlugin
      web:
        default_package: firebase_analytics_web
# This version is not null-safe but has been created to allow compatibility with already null-safe FlutterFire packages such as `firebase_core`.
